jobs:
    main:
        requires: [~pr, ~commit]
        image: node:18
        steps:
            - check: |
                ### do a check on what files changed here
                ### if no need to run subsequent tests then fail early
                meta set meta.status.certifyPR '{"status":"SUCCESS","message":"Coverage is above 80%."}'
                exit 1
            - teardown-step: |
                ### else run all steps and set success in teardown
                meta set meta.status.certifyPR '{"status":"SUCCESS","message":"Coverage is above 80%."}'
